<!DOCTYPE html>
<html>
<head>
    <title>require.js: Global Child Error Catch Test (debug mode enabled)</title>
    <script type="text/javascript" src="../../require.js"></script>
    <script type="text/javascript" src="../doh/runner.js"></script>
    <script type="text/javascript" src="../doh/_browserRunner.js"></script>
    <script type="text/javascript">
        var master = new doh.Deferred(),
            failed;

        function done() {
            if (failed) {
                master.callback(true);
            }
        }
        define('a', ['missing'], function(m) {
            return {};
        });

        requirejs.onError = function (err) {

            if (typeof new Error().stack !== 'undefined') {
                doh.t(typeof err.callStack === 'string');
            }

            failed = true;
        };

        require({
            debugMode: true
        },['a'], function (a) {
            failed = false;
        });

        setTimeout(done, 500);

        doh.register(
            "globalErrorChildDebugMode",
            [
                {
                    name: "globalErrorChildDebugMode",
                    timeout: 1000,
                    runTest: function () {
                        return master;
                    }
                }
            ]
        );
        doh.run();
    </script>
</head>
<body>
    <h1>require.js: Global Child Error Catch Test (debug mode enabled)</h1>
    <p>A top level require catches an error generated by a dependency (with global error callback).
        <a href="https://github.com/jrburke/requirejs/issues/1265">More info</a>.</p>
    <p>Check console for messages</p>
</body>
</html>
